export const SEED_PATHS = [
  {
    name: "7-Day Vision Clarity",
    description: "Sharpen your dream life vision through focused daily prompts",
    duration: 7,
    category: "vision",
    prompts: [
      { day: 1, prompt: "Describe your ideal day 5 years from now, from waking to sleeping." },
      { day: 2, prompt: "What does your dream career look like? How does it make you feel?" },
      { day: 3, prompt: "Describe the relationships in your ideal life. Who surrounds you?" },
      { day: 4, prompt: "What does peak health and energy feel like to you?" },
      { day: 5, prompt: "Imagine financial freedom. What changes? What stays the same?" },
      { day: 6, prompt: "What creative expression does your ideal self engage in?" },
      { day: 7, prompt: "Looking at your full vision, what's the first step you can take today?" },
    ],
  },
  {
    name: "5-Day Emotional Awareness",
    description: "Develop deeper awareness of your emotional patterns",
    duration: 5,
    category: "emotional",
    prompts: [
      { day: 1, prompt: "What emotion do you feel most often? When did it start?" },
      { day: 2, prompt: "Write about a time you felt truly at peace. What made it possible?" },
      { day: 3, prompt: "What triggers your strongest negative emotions? Explore without judgment." },
      { day: 4, prompt: "How do you express joy? When did you last feel it fully?" },
      { day: 5, prompt: "Write a letter to an emotion you struggle with. What would you say?" },
    ],
  },
  {
    name: "7-Day Gratitude Deep Dive",
    description: "Go beyond surface gratitude into transformative appreciation",
    duration: 7,
    category: "gratitude",
    prompts: [
      { day: 1, prompt: "List 10 things you're grateful for. Then pick one and go deep--why this one?" },
      { day: 2, prompt: "Write about a difficult experience you're now grateful for." },
      { day: 3, prompt: "Who has shaped you most? Write what you'd tell them." },
      { day: 4, prompt: "What about your body are you grateful for today?" },
      { day: 5, prompt: "Write about a small, easily-overlooked blessing in your daily life." },
      { day: 6, prompt: "What skill or talent are you grateful to have developed?" },
      { day: 7, prompt: "Write a gratitude letter to your future self." },
    ],
  },
  {
    name: "5-Day Goal Activation",
    description: "Transform vague goals into concrete, activated plans",
    duration: 5,
    category: "goals",
    prompts: [
      { day: 1, prompt: "What is one goal you've been putting off? Why?" },
      { day: 2, prompt: "Break that goal into the smallest possible first step. What is it?" },
      { day: 3, prompt: "What fears or beliefs are blocking you from this goal?" },
      { day: 4, prompt: "Imagine you've achieved the goal. How does your life differ?" },
      { day: 5, prompt: "Write your commitment: 'I will ___ by ___ because ___.'" },
    ],
  },
  {
    name: "7-Day Self-Discovery",
    description: "Explore who you are beneath the surface",
    duration: 7,
    category: "discovery",
    prompts: [
      { day: 1, prompt: "What did you love doing as a child that you've stopped doing?" },
      { day: 2, prompt: "What would you do if no one was watching or judging?" },
      { day: 3, prompt: "What beliefs about yourself have you outgrown?" },
      { day: 4, prompt: "Describe yourself through the eyes of someone who loves you." },
      { day: 5, prompt: "What's a part of yourself you've been hiding? Why?" },
      { day: 6, prompt: "What does 'success' truly mean to you--not society's definition?" },
      { day: 7, prompt: "Write a manifesto for the person you're becoming." },
    ],
  },
];
